# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{ copyPathToStore
, fetchFromGitHub
, fetchgit
, fetchurl
, ...
}:
{
  "@orpc/client@1.14.13" = fetchurl {
    url = "https://registry.npmjs.org/@orpc/client/-/client-1.14.13.tgz";
    hash = "sha512-IQoNxUHYlUfxejjAHFzH+KppwYm4sqJXdbL3143Up9yfOaP+onCpLpHfg2cXZB7NUDLXx7MLC40g96p997ZyNQ==";
  };
  "@orpc/contract@1.14.13" = fetchurl {
    url = "https://registry.npmjs.org/@orpc/contract/-/contract-1.14.13.tgz";
    hash = "sha512-VFQWUq62MTp1CB/cmEugUIJygxKj5lZSqF7SWbws7AGgeuUz77d5003pHqfGW3SR/Lj06Fg+xZdd9MlMoyweEw==";
  };
  "@orpc/interop@1.14.13" = fetchurl {
    url = "https://registry.npmjs.org/@orpc/interop/-/interop-1.14.13.tgz";
    hash = "sha512-5fw58f9xK6thcMMXX8aG3LFzKsfObZwHTyrt7/8jDIKHWUFalqIhs5kuEICmx7D+PbEWnlcdFt31oxN1vkSGFw==";
  };
  "@orpc/server@1.14.13" = fetchurl {
    url = "https://registry.npmjs.org/@orpc/server/-/server-1.14.13.tgz";
    hash = "sha512-4By45qm9Rzm/aWxJ7FZ3VKRFgbgNe2AzWqKrZOaQGl3wF/+nva58Srh3wWeHN1jqqEVE3Sz533IASkaUtfozMQ==";
  };
  "@orpc/shared@1.14.13" = fetchurl {
    url = "https://registry.npmjs.org/@orpc/shared/-/shared-1.14.13.tgz";
    hash = "sha512-RFOHhGHsIQkkGUHXQPqxdvKAuFWyk2c7KQPrf0ln1yC0TrC1Y/25XE1kql1McQmlBRegTlyeXYSTeQtEeFBq4g==";
  };
  "@orpc/standard-server-aws-lambda@1.14.13" = fetchurl {
    url = "https://registry.npmjs.org/@orpc/standard-server-aws-lambda/-/standard-server-aws-lambda-1.14.13.tgz";
    hash = "sha512-6ucBCwlBZptVhWjFnLgeakrvUwVOr6M22LX+S6pYolEv2gfi173szvgxX5Cyz+1VAtGvIWLQ3P6/KYjq6IVQLw==";
  };
  "@orpc/standard-server-fastify@1.14.13" = fetchurl {
    url = "https://registry.npmjs.org/@orpc/standard-server-fastify/-/standard-server-fastify-1.14.13.tgz";
    hash = "sha512-Cc++msIipb/3ee1q2ywzmHHirBUSiqZhJti4wwijK8ktnUXUR8bUVZ1v+6bXY38bKTIoT0bvY4D6bYarHCizuw==";
  };
  "@orpc/standard-server-fetch@1.14.13" = fetchurl {
    url = "https://registry.npmjs.org/@orpc/standard-server-fetch/-/standard-server-fetch-1.14.13.tgz";
    hash = "sha512-HREtKHD9WcDY81yUUEJXd3GLR+GlOd7sZryLkKo1p2NzhKwVgh/w7AmejY1DjWhND7eW9C6a3pkCsxM5ozcsEg==";
  };
  "@orpc/standard-server-node@1.14.13" = fetchurl {
    url = "https://registry.npmjs.org/@orpc/standard-server-node/-/standard-server-node-1.14.13.tgz";
    hash = "sha512-yQbqgW5ybdqLxKZA/tuaaRh1VfBPo8cn+HUotzwpAmoS8N1kAzkKktfs4TX28V/K+1Bkfrz4KyLpycmAtM8dyA==";
  };
  "@orpc/standard-server-peer@1.14.13" = fetchurl {
    url = "https://registry.npmjs.org/@orpc/standard-server-peer/-/standard-server-peer-1.14.13.tgz";
    hash = "sha512-RzPRDg4mccgWePhK9yTijeqxir0QNEeCdAzVkPuTlfsI1AlAnjTDcc0T4mpROSSEJqJhPZ2TDBqXw5zhLS5liw==";
  };
  "@orpc/standard-server@1.14.13" = fetchurl {
    url = "https://registry.npmjs.org/@orpc/standard-server/-/standard-server-1.14.13.tgz";
    hash = "sha512-7PrIuiYw1GB9mJwbO7ukc7WxeIqO1xulDdshkpd5DhalGRdIaaI4OVvE0Mt8biC9niGSoQSzCavD/PDwutgbzA==";
  };
  "@preact/signals-core@1.14.4" = fetchurl {
    url = "https://registry.npmjs.org/@preact/signals-core/-/signals-core-1.14.4.tgz";
    hash = "sha512-HNB6HYeYKhQbJ1aKl+YRjrS4+QWHLKX6qKoUsfS/m0vqzsVaEBiZiaKbG/e+NKk2ch5ALQr/ihWaMHxiCuuWHA==";
  };
  "@standard-schema/spec@1.1.0" = fetchurl {
    url = "https://registry.npmjs.org/@standard-schema/spec/-/spec-1.1.0.tgz";
    hash = "sha512-l2aFy5jALhniG5HgqrD6jXLi/rUWrKvqN/qJx6yoJsgKhblVd+iqqU4RCXavm/jPityDo5TCvKMnpjKnOriy0w==";
  };
  "cookie@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/cookie/-/cookie-1.1.1.tgz";
    hash = "sha512-ei8Aos7ja0weRpFzJnEA9UHJ/7XQmqglbRwnf2ATjcB9Wq874VKH9kfjjirM6UhU2/E5fFYadylyhFldcqSidQ==";
  };
  "drishti-agent" = copyPathToStore ./.;
  "drishti-common" = copyPathToStore ../common;
  "openapi-types@12.1.3" = fetchurl {
    url = "https://registry.npmjs.org/openapi-types/-/openapi-types-12.1.3.tgz";
    hash = "sha512-N4YtSYJqghVu4iek2ZUvcN/0aqH1kRDuNqzcycDxhOUpg7GdvLa2F3DgS6yBNhInhv2r/6I0Flkn7CqL8+nIcw==";
  };
  "radash@12.1.1" = fetchurl {
    url = "https://registry.npmjs.org/radash/-/radash-12.1.1.tgz";
    hash = "sha512-h36JMxKRqrAxVD8201FrCpyeNuUY9Y5zZwujr20fFO77tpUtGa6EZzfKw/3WaiBX95fq7+MpsuMLNdSnORAwSA==";
  };
  "tagged-tag@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/tagged-tag/-/tagged-tag-1.0.0.tgz";
    hash = "sha512-yEFYrVhod+hdNyx7g5Bnkkb0G6si8HJurOoOEgC8B/O0uXLHlaey/65KRv6cuWBNhBgHKAROVpc7QyYqE5gFng==";
  };
  "type-fest@5.8.0" = fetchurl {
    url = "https://registry.npmjs.org/type-fest/-/type-fest-5.8.0.tgz";
    hash = "sha512-YGYEVz3Fm5iy/AybuA0oyNFq7H4CgQNfRp/qfe8nurE1kuCeNm3/vfm9X4Mtl+qLyaKJUh5xrFZwogr41SMjYA==";
  };
  "zod@4.4.3" = fetchurl {
    url = "https://registry.npmjs.org/zod/-/zod-4.4.3.tgz";
    hash = "sha512-ytENFjIJFl2UwYglde2jchW2Hwm4GJFLDiSXWdTrJQBIN9Fcyp7n4DhxJEiWNAJMV1/BqWfW/kkg71UDcHJyTQ==";
  };
}
